services:
  postgres:
    container_name: postgres-sql-auth
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
      POSTGRES_DB: authentication
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-auth
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

  keycloak:
    container_name: keycloak-auth
    image: quay.io/keycloak/keycloak:26.1.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/authentication
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: Admin
      KEYCLOAK_SMTP_HOST: smtp.gmail.com
      KEYCLOAK_SMTP_PORT: 465
      KEYCLOAK_SMTP_USER: "celina.celine999@gmail.com"
      KEYCLOAK_SMTP_PASSWORD: "pcnpyxvwembigxwb"
      KEYCLOAK_SMTP_FROM: "benromdhan.azza99@gmail.com"
      KEYCLOAK_SMTP_TLS: "true"
    networks:
      - spring-demo
    depends_on:
      - postgres
    command:
      - "start-dev"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local